---
# tasks file for hosts

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == 'FreeBSD'

- include: hostname.yml
# Docker does not let you modify /etc/hosts
- include: hosts.yml
  when: ansible_virtualization_type != 'docker'