---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: test.mydomain.net
    image: "ubuntu:bionic"
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: inspec
  lint:
    name: rubocop
